### ISSUE TITLE
request for kooplearn

### ISSUE THREAD

**Issue by NYF1998** [mitchellostrow/DSA#5]
Hello author, while reproducing the DSA code, I found that the kooplearn package in kerneldmd.py could not be found in the Python library. Can you provide resources for this package? Thank you.

**Comment by mitchellostrow** [comment]
https://github.com/Machine-Learning-Dynamical-Systems/kooplearn

It should be installable via pip

**Comment by NYF1998** [comment]
您好，您的邮件我已收到。牛一帆  北京师范大学人工智能学院15510202789
